# -*- coding: utf-8 -*-
"""GCN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDTxSRTRuI2x38GxjWxJUqO_4UnMGMY1
"""

import numpy as np

H = np.array([[0.20,0.60,0.30,-0.40],
              [0.40,0.30,-0.20,-0.60],
              [0.20,-0.60,0.50,-0.30],
              [-0.40,0.20,0.20,-0.40],
              [0.70,-0.90,0.10,-0.50],
              [0.30,0.50,-0.30,0.70],
              [0.90,-0.60,0.20,-0.80],
              [-0.10,0.70,0.10,-0.90]])
A = np.array([[0,1,1,0,1,0,0,0],
              [1,0,1,1,0,1,0,0],
              [1,1,0,0,0,1,1,0],
              [0,1,0,0,1,0,0,0],
              [1,0,0,1,0,0,1,1],
              [0,1,1,0,0,0,1,0],
              [0,0,1,0,1,1,0,1],
              [0,0,0,0,1,0,1,0]])
W = np.array([[1,0,0,0],
              [1,1,0,0],
              [1,1,1,0],
              [1,1,1,1]])
B = np.array([[1,0,0,1],
              [1,0,1,0],
              [0,0,1,1],
              [1,0,1,0]])

print(A)

Degree = (np.array(A.sum(1),dtype=np.float32))
print(Degree)

D_1 = np.diag(np.power(Degree, -1))
print(D_1)

A_hat = D_1.dot(A)
print(A_hat)

print(A_hat.dot(H))

print((A_hat.dot(H)).dot(W.T))

print(H.dot(B.T))

H_1 = (A_hat.dot(H)).dot(W.T)+H.dot(B.T)
print(H_1)

def relu(x):
    return np.maximum(0, x)

print(relu(H_1))